.\" Pipe this output to groff -Tutf8 | less
.\"
.mso an.tmac
.TH "dune-unstable-fmt" 1 "" "Dune 1.2.1" "Dune Manual"
.\" Disable hyphenation and ragged-right
.nh
.ad l
.SH NAME
.P
dune\N'45'unstable\N'45'fmt \N'45' Format dune files
.SH SYNOPSIS
.P
\fBdune unstable\N'45'fmt\fR [\fIOPTION\fR]\N'46'\N'46'\N'46' [\fIFILE\fR]
.SH DESCRIPTION
.P
\fBdune unstable\N'45'fmt\fR reads a dune file and outputs a formatted version\N'46' This feature is unstable, and its interface or behaviour might change\N'46' 
.SH ARGUMENTS
.TP 4
\fIFILE\fR
Path to the dune file to parse\N'46'
.SH OPTIONS
.TP 4
\fB\N'45'\N'45'help\fR[=\fIFMT\fR] (default=auto)
Show this help in format \fIFMT\fR\N'46' The value \fIFMT\fR must be one of `auto\N'39', `pager\N'39', `groff\N'39' or `plain\N'39'\N'46' With `auto\N'39', the format is `pager` or `plain\N'39' whenever the \fBTERM\fR env var is `dumb\N'39' or undefined\N'46'
.TP 4
\fB\N'45'\N'45'inplace\fR
Modify the file in place
.TP 4
\fB\N'45'\N'45'version\fR
Show version information\N'46'